package com.kyouseipro.neo.common.enums.system;

public enum QueryKind {
    SQL,
    OPERATIONS,
    DELETE_BY_IDS,
    INSERT,
    UPDATE,
    SAVE,
    CSV,
    
    ORDER_SAVE,
    ORDER_ITEM_ARRIVAL,
    ORDER_ITEM_SAVE,

    DAILY_CREW_BULK_CREATE,

    DISPATCH_ASSIGNMENT_REORDER,

    RECYCLE_DELIVERY_SAVE,
    RECYCLE_SHIPPING_SAVE,
    RECYCLE_LOSS_SAVE,
    RECYCLE_PRICE_LIST,
    RECYCLE_PRICE_SAVE,
    RECYCLE_PRICE_DETAIL
}
